r"""
generated by json2python-models v0.3.1 at Thu Nov 20 11:55:37 2025
command: /data/data/com.termux/files/usr/bin/json2models -f base -s nested -m DriverStanding raw.json
"""
from json_to_models.dynamic_typing import IntString
from typing import Literal, Optional, Union


class DriverStanding:
    class Room:
        id_: int
        code: Union[IntString, Literal["1B", "1C", "2B", "2C", "3B", "3C", "4B", "SG"]]

    class TimeSlot:
        id_: int
        start: Literal["08:00", "08:55", "09:50", "10:50", "11:45", "12:40", "13:40", "14:35", "15:30"]
        end: Literal["08:45", "09:40", "10:35", "11:35", "12:30", "13:25", "14:25", "15:20", "16:15"]
        display: Literal["08:00-08:45", "08:55-09:40", "09:50-10:35", "10:50-11:35", "11:45-12:30", "12:40-13:25", "13:40-14:25", "14:35-15:20", "15:30-16:15"]
        position: int

    class Subject:
        id_: int
        key: str
        name: str
        kod: str
        position: int

    class TeacherPrimary:
        id_: int
        surname: str
        name: str
        display_name: str

    class Date:
        timestamp: int
        Date: Literal["2025-11-14", "2025-11-17", "2025-11-18", "2025-11-19", "2025-11-20", "2025-11-21"]
        date_display: Literal["14.11.2025", "17.11.2025", "18.11.2025", "19.11.2025", "20.11.2025", "21.11.2025"]
        time_: Literal["00:00:00", "08:26:33", "09:06:20", "11:24:04"]

    class Change:
        id_: int
        type_: int
        is_merge: bool
        separation: bool

    class Clazz:
        id_: int
        key: str
        display_name: Literal["1TPI"]
        symbol: Literal["TPI"]

    class Distribution:
        id_: int
        key: str
        shortcut: Literal["CH", "PROG", "REL"]
        name: Literal["Ch\u0142opiec", "Programista", "Religia"]
        part_type: Literal["kryterium", "p\u0142e\u0107 m\u0119ska"]

    id_: int
    date_at: Literal["2025-11-17", "2025-11-18", "2025-11-19", "2025-11-20", "2025-11-21"]
    event: None
    teacher_secondary: None
    teacher_secondary2: None
    change: 'Change'
    clazz: 'Clazz'
    unit_id: Optional[int]
    schedule_id: Optional[int]
    lesson_date: Optional['Date']
    change_date: Optional[None]
    change_date_at: Optional[None]
    pupil_note: Optional[None]
    reason: Optional[None]
    room: Optional['Room']
    time_slot: Optional['TimeSlot']
    subject: Optional['Subject']
    teacher_primary: Optional['TeacherPrimary']
    teacher_absence_reason_id: Optional[int]
    teacher_absence_effect_name: Optional[str]
    teacher_secondary_absence_reason_id: Optional[None]
    teacher_secondary_absence_effect_name: Optional[None]
    teacher_secondary2_absence_reason_id: Optional[None]
    teacher_secondary2_absence_effect_name: Optional[None]
    distribution: Optional['Distribution']
    class_absence: Optional[bool]
    no_room: Optional[bool]
    date_modified: Optional['Date']
    modified_at: Optional[str]
    description: Optional[None]
    merge_change_id: Optional[None]
    date_: Optional['Date']
    pupil_alias: Optional[None]
    visible: Optional[bool]
    substitution: Optional['DriverStanding']
    parent: Optional[None]

